// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-workspaces.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Reconnect this MCP server and sign in." }],
    isError: true
  };
}

// src/lib/mcp/tools/list-workspaces.ts
var list_workspaces_default = defineTool({
  name: "list_workspaces",
  title: "List workspaces",
  description: "List the ventures/organisations (workspaces) the signed-in user belongs to, with slug, name, role and status.",
  inputSchema: {
    include_archived: z.boolean().optional().describe("Include archived workspaces. Defaults to false.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_archived }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("kova_orgs").select("slug, name, role, status, color").order("position", { ascending: true });
    if (!include_archived) query = query.neq("status", "archived");
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { workspaces: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_tasks_default = defineTool2({
  name: "list_tasks",
  title: "List tasks",
  description: "List the signed-in user's tasks, optionally filtered by workspace slug and state.",
  inputSchema: {
    org: z2.string().optional().describe("Workspace slug from list_workspaces. Omit for all workspaces."),
    state: z2.enum(["todo", "doing", "blocked", "done"]).optional().describe("Filter by task state."),
    limit: z2.number().int().min(1).max(100).optional().describe("Max rows. Defaults to 25.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ org, state, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("kova_tasks").select("id, title, org, project, state, priority, assignee, due_at, created_at").order("due_at", { ascending: true, nullsFirst: false }).limit(limit ?? 25);
    if (org) query = query.eq("org", org);
    if (state) query = query.eq("state", state);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var create_task_default = defineTool3({
  name: "create_task",
  title: "Create task",
  description: "Create a task for the signed-in user in one of their workspaces.",
  inputSchema: {
    title: z3.string().trim().min(1).max(300).describe("What needs doing."),
    org: z3.string().optional().describe("Workspace slug from list_workspaces. Omit for a cross-workspace task."),
    project: z3.string().optional().describe("Project name this task belongs to."),
    priority: z3.enum(["low", "medium", "high"]).optional().describe("Defaults to medium."),
    due_at: z3.string().datetime().optional().describe("ISO 8601 due date/time.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ title, org, project, priority, due_at }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data: tenantId, error: tenantError } = await supabase.rpc("current_tenant_id");
    if (tenantError || !tenantId) {
      return {
        content: [{ type: "text", text: "Could not resolve your workspace tenant. Open the app once, then retry." }],
        isError: true
      };
    }
    const { data, error } = await supabase.from("kova_tasks").insert({
      tenant_id: tenantId,
      user_id: ctx.getUserId(),
      title,
      org: org ?? "__any",
      project: project ?? null,
      priority: priority ?? "medium",
      due_at: due_at ?? null
    }).select("id, title, org, project, state, priority, due_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created task "${data.title}".` }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/tools/search-knowledge.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var search_knowledge_default = defineTool4({
  name: "search_knowledge",
  title: "Search knowledge base",
  description: "Full-text search across the signed-in user's knowledge documents. Returns matching titles and excerpts.",
  inputSchema: {
    query: z4.string().trim().min(2).describe("Words to look for in document titles and bodies."),
    org: z4.string().optional().describe("Workspace slug to restrict the search to."),
    limit: z4.number().int().min(1).max(25).optional().describe("Max documents. Defaults to 8.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, org, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const term = query.replace(/[%,]/g, " ").trim();
    let q = supabase.from("kova_documents").select("id, title, category, org, source, body, updated_at").or(`title.ilike.%${term}%,body.ilike.%${term}%`).order("updated_at", { ascending: false }).limit(limit ?? 8);
    if (org) q = q.eq("org", org);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const results = (data ?? []).map((d) => {
      const body = d.body ?? "";
      const at = body.toLowerCase().indexOf(term.toLowerCase());
      const start = at > 120 ? at - 120 : 0;
      return {
        id: d.id,
        title: d.title,
        category: d.category,
        org: d.org,
        source: d.source,
        updated_at: d.updated_at,
        excerpt: body.slice(start, start + 400)
      };
    });
    if (results.length === 0) {
      return { content: [{ type: "text", text: `No documents matched "${term}".` }], structuredContent: { results } };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { results }
    };
  }
});

// src/lib/mcp/tools/list-contacts.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_contacts_default = defineTool5({
  name: "list_contacts",
  title: "List contacts",
  description: "List or search the signed-in user's contacts, with company, role and confidence score.",
  inputSchema: {
    search: z5.string().trim().min(1).optional().describe("Match against name or company."),
    org: z5.string().optional().describe("Workspace slug to filter by."),
    limit: z5.number().int().min(1).max(100).optional().describe("Max rows. Defaults to 25.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, org, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("kova_contacts").select("id, name, role, company, org, confidence, scanned_at").order("scanned_at", { ascending: false, nullsFirst: false }).limit(limit ?? 25);
    if (org) q = q.eq("org", org);
    if (search) {
      const term = search.replace(/[%,]/g, " ").trim();
      q = q.or(`name.ilike.%${term}%,company.ilike.%${term}%`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { contacts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-agent-proposals.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var list_agent_proposals_default = defineTool6({
  name: "list_agent_proposals",
  title: "List agent proposals",
  description: "List proposals agents have raised for the signed-in user, with rationale, confidence and approval state. Read-only \u2014 approving a proposal stays a human action inside the app.",
  inputSchema: {
    org: z6.string().optional().describe("Workspace slug to filter by."),
    state: z6.string().optional().describe("Filter by proposal state, e.g. 'pending'."),
    limit: z6.number().int().min(1).max(50).optional().describe("Max rows. Defaults to 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ org, state, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("kova_proposals").select("id, agent, org, ref, proposal, rationale, confidence, signals, state, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (org) q = q.eq("org", org);
    if (state) q = q.eq("state", state);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { proposals: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qzurwsqecdsgziyvnuul";
var mcp_default = defineMcp({
  name: "kova-io",
  title: "Kova io",
  version: "0.1.0",
  instructions: "Tools for Kova, a multi-venture operating system. Call `list_workspaces` first to learn the workspace slugs, then filter tasks, contacts, knowledge and agent proposals by that slug. All data is scoped to the signed-in user. Agent proposals are read-only: a person approves them inside Kova.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_workspaces_default,
    list_tasks_default,
    create_task_default,
    search_knowledge_default,
    list_contacts_default,
    list_agent_proposals_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
